baseurl: ''
url: 'https://tealowllabs.com/'
permalink: pretty
title: 'Teal Owl Labs'

# logo:
#   mobile: "images/logo/logo-mobile.svg"
#   mobile_height: "32px"
#   mobile_width: "32px"
#   desktop: "images/logo/logo.svg"
#   desktop_height: "32px"
#   desktop_width: "120px"

collections:


defaults:
  - scope:
      path: "#services"
      type: ""
    values:
      layout: ""

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
