services:
  development:
    - name: Application Development
      blurb: a
    - name: Backend Development
      blurb: a
    - name: Data Pipelines
      blurb: a
    - name: Enterprise Applications
      blurb: a
    - name: PoC Development
      blurb: a
  testing:
    - name: Accessibility Testing
      blurb: a
    - name: Automated Testing
      blurb: a
    - name: Performance Testing
      blurb: a
  audit:
    - name: Accessibility Evaluation
      blurb: a
    - name: Manual Mobile Testing
      blurb: a
    - name: SEO Audit
      blurb: a
    - name: User Experience Review
      blurb: a
  process:
    - name: Support and Altering Development
      blurb: a
    - name: CI/CD Pipeline Implementation
      blurb: a
    - name: Observability and Dashboard Development
      blurb: a
    - name: Automated Testing Improvements
      blurb: a
  website:
    - name: E-Commerce Site Development
      blurb: a
    - name: Website Development
      blurb: a
  design:
    - name: Architecture Assessment
      blurb: a
    - name: Code Review
      blurb: a
    - name: Documentation Review
      blurb: a